### ISSUE TITLE
Silent crash when syncing an entry without content.

### ISSUE THREAD

**Issue by casimir** [casimir/frigoligo#26]
Reported by @nicosomb on matrix.
```
flutter: [2023-08-02 16:22:48.988491] INFO wallabag.client fetched entries (page 16 of 51)
[ERROR:flutter/runtime/dart_vm_[initializer.cc](http://initializer.cc/)(41)] Unhandled Exception: Null check operator used on a null value
#0      new Article.fromWallabagEntry (package:frigoligo/models/article.dart:42:32)
#1      ArticlesProvider.fullRefresh (package:frigoligo/services/wallabag.dart:173:48)
<asynchronous suspension>
```
https://github.com/casimir/frigoligo/blob/d093cae0d4cddbd5d3a424dc521e560602d25a81/lib/models/article.dart#L42

**Comment by casimir** [comment]
Fixed by #30
